apiVersion: v1
kind: Namespace
metadata:
  name: airflow
  annotations:
    openshift.io/sa.scc.mcs: 's0:c26,c5'
    openshift.io/sa.scc.supplemental-groups: 1000710000/10000
    openshift.io/sa.scc.uid-range: 1000710000/10000
